name: headscale
base: core24
version: 0.26.1
license: BSD-3-Clause
grade: stable
confinement: strict
contact: solutions-engineering@lists.canonical.com
issues: https://github.com/canonical/headscale-snap/issues
summary: An open source, self-hosted implementation of the Tailscale control server
icon: docs/logo.png
description: |
  See https://headscale.net/ for upstream documentation.

  **Getting started**

  Install the snap:

     sudo snap install headscale

  The snap provides a headscale service (`headscale serve`) with an initial example configuration, started automatically on install.
  It also provides the `headscale` command to interact with the service.
  You will need to configure the service by editing the configuration file at `/var/snap/headscale/common/config.yaml`.
  See https://github.com/canonical/headscale-snap/blob/main/docs/config-reference.md for more information on configuration.

  **Security**

  See https://github.com/canonical/headscale-snap/blob/main/docs/security-reference.md
  for security and hardening documentation.

  This snap is maintained by Canonical, and is not necessarily endorsed or officially maintained by the upstream developers.


platforms:
  amd64:
  arm64:

environment:
  HEADSCALE_CONFIG: $SNAP_COMMON/config.yaml

apps:
  headscaled:
    command: bin/headscale serve
    daemon: simple
    plugs:
      - network
      - network-bind
  headscale:
    command: bin/headscale
    plugs:
      - network
      - network-bind

parts:
  headscale:
    source: https://github.com/juanfont/headscale.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: go
    build-snaps:
      - go
    stage-packages:
      - jq  # for rendering the config file
    override-build: |
      go install -p $CRAFT_PARALLEL_BUILD_COUNT ./cmd/headscale
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      default-config.yaml: etc/
