name: headscale
base: core24
version: 0.23.0
license: BSD-3-Clause
grade: stable
confinement: strict
contact: solutions-engineering@lists.canonical.com
issues: https://github.com/canonical/headscale-snap/issues
summary: An open source, self-hosted implementation of the Tailscale control server
description: |
  See https://headscale.net/ for upstream documentation.

  **Getting started**

  Install the snap:

     sudo snap install headscale

  The snap provides a headscale service (`headscale serve`), with an initial configuration, which is started automatically on install.
  It also provides the `headscale` command to interact with the service.
  You will need to configure the service via snap config; see https://github.com/canonical/headscale-snap/blob/main/docs/config-reference.md for more information.

  **Security**

  The snap is strictly confined, and requires the following interfaces:

  * network: general network access.
  * network-bind: required for listening on a network interface.

  The snap provides some wrappers to manage configuration; these do not directly use any cryptographic functionality.
  Please see upstream docs for information about security of Headscale itself.

platforms:
  amd64:

environment:
  HEADSCALE_CONFIG: $SNAP_COMMON/internal/config.yaml

apps:
  headscaled:
    command: bin/headscale serve
    daemon: simple
    plugs:
      - network
      - network-bind
  headscale:
    command: bin/headscale
    plugs:
      - network
      - network-bind

parts:
  headscale:
    source: https://github.com/juanfont/headscale.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: go
    build-snaps:
      - go
    stage-packages:
      - jq  # for rendering the config file
    override-build: |
      go install -p $CRAFT_PARALLEL_BUILD_COUNT ./cmd/headscale
